wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.7.12
    cli_version: 0.17.7
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1725421992
    t:
      1:
      - 3
      - 55
      3:
      - 23
      4: 3.7.12
      5: 0.17.7
      8:
      - 5
      13: linux-x86_64
