wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.7.12
    cli_version: 0.17.7
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1726819561
    t:
      1:
      - 3
      - 55
      2:
      - 3
      - 5
      - 53
      - 55
      3:
      - 17
      - 23
      - 37
      4: 3.7.12
      5: 0.17.7
      8:
      - 5
      10:
      - 3
      13: linux-x86_64
iterations:
  desc: null
  value: 1
batch_size:
  desc: null
  value: 24
hidden_dim:
  desc: null
  value: 12
num_layers:
  desc: null
  value: 3
